export const TOOLS = [
  {
    href: "/paycheck/",
    icon: "💰",
    name: "Paycheck Calculator",
    description: "Estimate your take-home pay after federal tax, state tax, Social Security, and Medicare.",
    color: "from-green-500 to-emerald-600",
  },
  {
    href: "/shift/",
    icon: "📅",
    name: "Shift Work Schedule",
    description: "Generate a 4-week calendar for Panama, Pitman, 4-on-4-off, and DuPont rotations.",
    color: "from-blue-500 to-indigo-600",
  },
  {
    href: "/pace/",
    icon: "🏃",
    name: "Running Pace Calculator",
    description: "Calculate pace, predict finish times, and forecast race results using the Riegel formula.",
    color: "from-orange-500 to-red-500",
  },
  {
    href: "/pregnancy/",
    icon: "🤰",
    name: "Pregnancy Calculator",
    description: "Find your due date, current week, trimester milestones, and fertile window.",
    color: "from-pink-500 to-rose-500",
  },
  {
    href: "/contrast/",
    icon: "🎨",
    name: "Color Contrast Checker",
    description: "Check WCAG AA/AAA contrast ratios for text and get suggested accessible color alternatives.",
    color: "from-purple-500 to-violet-600",
  },
  {
    href: "/loan/",
    icon: "🏦",
    name: "Loan Calculator",
    description: "Calculate monthly payments and total interest for any loan or mortgage.",
    color: "from-blue-500 to-blue-600",
  },
  {
    href: "/tip/",
    icon: "🧾",
    name: "Tip Calculator",
    description: "Split the bill and calculate tip for any party size.",
    color: "from-orange-500 to-amber-600",
  },
  {
    href: "/bmi/",
    icon: "⚖️",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and healthy weight range.",
    color: "from-teal-500 to-cyan-600",
  },
  {
    href: "/convert/",
    icon: "🔄",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, and volume between any units.",
    color: "from-violet-500 to-purple-600",
  },
  {
    href: "/age/",
    icon: "🎂",
    name: "Age Calculator",
    description: "Find your exact age in years, months, and days — or the difference between any two dates.",
    color: "from-pink-500 to-rose-600",
  },
];
